### PR TITLE
Update DG to include delete book and overdue book feature

### PR DESCRIPTION
**Pull request by GJ0407790**

### CODE REVIEW

**Comment by Andrewzhang217** [comment]
Please fix the checkstyle error before merging to master branch

**Comment by GJ0407790** [comment]
Seems like my checkstyle not running in DeveloperGuide.md

**Comment by GJ0407790** [comment]
@Andrewzhang217 I never add a new line at EOF in one of my puml file. It's fixed now. Thanks

**Comment by Andrewzhang217** [comment]
This pull request looks good to me and can be merged to the master branch of our team repository

**Pull request merged**
